apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasura-postgres
  labels:
    app: hasura-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura-postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hasura-postgres
    spec:
      containers:
        - name: hasura-postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: supersecret
          # TO BE COMPLETED: Add a liveness probe for postgresql.
---
apiVersion: v1
kind: Service
metadata:
  name: hasura-postgres-service
spec:
  selector:
    app: hasura-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432